config/routes.rb
DigitalERP::Application.routes.draw do

  resources :products
  resources :product_brands
  resources :customers
  resources :suppliers
  resources :buys
  resources :sells
  
  root :to => 'products#index'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container hidden-print">
      <%# link_to "Digital Island", '#', id: "logo" %>
      <nav>
        <ul class="nav  pull-right">
          <li><%= link_to "Productos", products_path %></li>              
          <li><%= link_to "Compras", buys_path %></li>              
          <li><%= link_to "Ventas", sells_path %></li>

          <!-- <li class="divider-vertical"></li> -->
          
          <li><%= link_to "Marca", new_product_brand_path %></li>              
          <li><%= link_to "Registrar Producto",  new_product_path %></li>  
          
          <!-- <li class="divider-vertical"></li> -->
          
          <li><%= link_to "Nuevo proveedor", new_supplier_path %></li>              
          <li><%= link_to "Comprar", new_buy_path %></li>              
          
          <!-- <li class="divider-vertical"></li> -->
          
          <li><%= link_to "Nuevo Cliente", new_customer_path %></li>              
          <li><%= link_to "Venta", new_sell_path %></li>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digital Island</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

  <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
        <!-- <div class="alert alert-<%= key %>"><%= value %></div> -->
        <%= content_tag(:div, value, class: "alert alert-#{key}" ) %>
      <% end %>

      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>